### ISSUE TITLE
Investigate the `await new Paratii` pattern

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-lib#117]
History: we add issues with too many websockets remaing open, which was fixed with PR  https://github.com/Paratii-Video/paratii-lib/pull/113

However, it is unclear, still, what excatly fxied this this issue: see this comment: https://github.com/Paratii-Video/paratii-lib/pull/113/files#diff-2f52e305eeec9d9c8aeb8f74e8f45605R8

**Comment by milankragujevic** [comment]
Seems that this was just a happy coincidence, as removing the `await` in all test files still doesn't break anything, so it seems that this is completely unnecessary. 

Also, it looks like the key is in `lib/paratii.js` and `lib/paratii.eth.js`, as the detection of test net and also setup of provider was improved to correctly identify the URLs.
