### ISSUE TITLE
what should the type of the `file` argumnet in `vids.create(..)` be?

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-lib#44]
https://github.com/Paratii-Video/paratii-lib/blob/master/docs/paratii-core.md

`core.vids.create(...)` takes a `file` argument  - which is the video to be uploaded and transcoded.

how shall we pass that file? At the moment, it is a path to a local file, but probably the best is to change the type to `filestream`.

(@ya7ya , what dayya say?)

**Comment by ya7ya** [comment]
hey @jellegerbrandy , I do agree it'd be best if it takes a `filestream` or more likely an HTML5 `File` Object since the browser doesn't have access to the filesystem and I think this will mainly be used in the browser.
