### ISSUE TITLE
progress is not reported correctly

### ISSUE THREAD

**Issue by mrocha94** [Paratii-Video/paratii-lib#71]
Also, in https://github.com/Paratii-Video/paratii-lib/blob/322d28f63875f203c9b34d06303136b3d763812c/lib/paratii.ipfs.uploader.browser.js#L89 always returns 0, it should be:

`pull.through((chunk) => opts.onProgress(chunk.length, Math.floor((meta.total + chunk.length) * 1.0 / meta.fileSize * 100)))`

**Comment by jellegerbrandy** [comment]
The first point (upload should return a promise)  is a duplicate of #69 , so I'll edit it out.
