### ISSUE TITLE
Force sealing can't be used with reseal_min_period = 0

### ISSUE THREAD

**Issue by milankragujevic** [Paratii-Video/paratii-lib#72]
`Force sealing can't be used with reseal_min_period = 0` when running `yarn parity` (Linux Mint 18.3 Sylvia amd64).

**Comment by jellegerbrandy** [comment]
I cannot reproduce this. It's probably related to https://github.com/paritytech/parity/issues/5803

@milankragujevic what version of parity?

@geckoslair : any ideas?

**Comment by milankragujevic** [comment]
@jellegerbrandy `Parity/v1.7.12-stable-f96d152-20180109/x86_64-linux-gnu/rustc1.22.1`, installed via .deb because the short command returns errors (https://github.com/paritytech/parity/issues/6548)

**Comment by milankragujevic** [comment]
Solved by updating Parity.
