### ISSUE TITLE
still missing a better event addressing for the event

### ISSUE THREAD

**Issue by geckoslair** [Paratii-Video/paratii-lib#89]
we would like to have specific event for a specific video creation?

**Comment by jellegerbrandy** [comment]
?

**Comment by geckoslair** [comment]
Just a stream of consciousness, i has noticed testing the events:

- Create and update video are triggered indifferently
- If i've hooked two ore more CreateEvent listener they are all triggered when a video is created. Maybe i want to hook a CreateEvent on a specific video.
- it seems that there is no (documented) way to remove a subscription

@jellegerbrandy, what you think? Just mental saws? :D

**Comment by jellegerbrandy** [comment]
- same event for update and create: yes. We could change that. Buit is it a problem?
- I don't thik you **can** have a subscription to a createevent for a sepcific video (especially not before it is created :-)). Also, I don't think we have a use case for that, do we?
- no unsubscribe: you mean in web3? Ok. Well, too bad, let's then also not hav ein in our API (I don't thnk we need it anyway)

**Comment by jellegerbrandy** [comment]
closing this as not actionable
