### ISSUE TITLE
implement `paratii.db.vids.get`

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-lib#99]
This function should get its info from the `paratii-db`.

At the momen,t `paratii.db.vids.get` is a place holder function that gets the information from paratii and the database.

The `paratii.config['db.provider']` should be  a link to `http://paratii-db.paratii.video/api/v1/`, an the videos should be fechted from there

**Comment by jellegerbrandy** [comment]
We should also find a way of testing this functionality - preferably not agains the production  server...

**Comment by geckoslair** [comment]
quiet finished, you can reviewed the PR https://github.com/Paratii-Video/paratii-lib/pull/104
